apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runners
spec:
  template:
    spec:
      image: ghcr.io/benzene-tech/github-runner:ubuntu-22.04
      imagePullSecrets:
        - name: github
      organization: benzene-tech
      labels:
        - benzene-ubuntu
      workDir: /home/runner/work
      containers:
        - name: runner
          resources:
            limits:
              cpu: "2.0"
              memory: "4Gi"
            requests:
              cpu: "1m"
              memory: "50Mi"
          securityContext:
            privileged: false
        - name: docker
          resources:
            limits:
              cpu: "4.0"
              memory: "8Gi"
            requests:
              cpu: "1m"
              memory: "50Mi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runners
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: github-runners
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '0.5'
