apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/benzene-tech/github-runners.git
      targetRevision: main
      ref: values
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.6.1
      helm:
        releaseName: arc
        valueFiles:
          - $values/arc/controller.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
