server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    ingressClassName: nginx
    https: true

configs:
  cm:
    dex.config: |
      connectors:
        - name: GitHub
          id: github
          type: github
          config:
            clientID: $dex.github.clientID
            clientSecret: $dex.github.clientSecret
            orgs:
              - name: benzene-tech
                teams:
                  - Admin
    admin.enabled: false

  rbac:
    policy.default: role:readonly

  credentialTemplates:
    github:
      url: https://github.com/benzene-tech
      username: Benzene
  repositories:
    github-runners:
      url: https://github.com/benzene-tech/github-runners
