githubConfigUrl: https://github.com/benzene-tech
githubConfigSecret: github-app

containerMode:
  type: dind

template:
  metadata:
    annotations:
      karpenter.sh/do-not-disrupt: 'true'
  spec:
    imagePullSecrets:
      - name: github-registry

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems
