name: Build Runner image

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build_image.yml"
      - "Dockerfile"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/build_image.yml"
      - "Dockerfile"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [ ubuntu-20.04, ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TAG=${{ matrix.tag }}
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          pull: true
          tags: ghcr.io/santhoshnath/github-runner:${{ matrix.tag }}
          cache-to: type=gha,ignore-error=true
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
