name: Build GitHub Runner image

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build_image.yml"
      - "Dockerfile"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/build_image.yml"
      - "Dockerfile"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [ ubuntu-22.04 ]
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/github-runner:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TAG=${{ matrix.tag }}
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          pull: true
          tags: ${{ env.IMAGE_NAME }}
          cache-to: type=gha,ignore-error=true
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64

      - name: Run Trivy vulnerability scanner
        env:
          TRIVY_USERNAME: ${{ github.repository_owner }}
          TRIVY_PASSWORD: ${{ github.token }}
        uses: aquasecurity/trivy-action@0.9.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: ${{ github.event_name == 'push' && 'sarif' || 'table' }}
          output: ${{ github.event_name == 'push' && 'trivy.sarif' || '' }}

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
