name: Build GitHub Runner image

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/image.yml"
      - "runner/Dockerfile"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/image.yml"
      - "runner/Dockerfile"
  schedule:
    - cron: "30 6 1 * *"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: github-runner

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image tag
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern=${{ github.ref_name }}
            type=ref,event=branch

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:runner'
          tags: ${{ env.IMAGE_NAME }}:latest
          load: true
          pull: true
          cache-to: type=gha,mode=max
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.18.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: ${{ github.event_name != 'pull_request' && 'sarif' || 'table' }}
          output: ${{ github.event_name != 'pull_request' && 'trivy.sarif' || '' }}

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:runner'
          tags: ${{ steps.metadata.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          push: true
