name: Install GitHub Runners

on:
  workflow_dispatch:

concurrency: install

jobs:
  Install:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name github_runners

      - name: Remove annotation from coredns deployment
        run: |
          compute_type=$(kubectl get deployment coredns -n kube-system -o jsonpath="{.spec.template.metadata.annotations.eks\.amazonaws\.com/compute-type}")
          if [ "$compute_type" == "ec2" ]; then
            kubectl patch deployment coredns \
              -n kube-system \
              --type json \
              -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
            kubectl rollout restart deployment coredns -n kube-system
          fi

      - name: Create GitHub secrets
        run: |
          kubectl create secret docker-registry github-registry \
            --docker-server=ghcr.io \
            --docker-username=${{ github.repository_owner }} \
            --docker-password=${{ secrets.GH_PACKAGES_TOKEN }}
          
          kubectl create secret generic github-app \
            -n arc-runners \
            --from-literal=github_app_id=${{ secrets.RUNNER_APP_ID }} \
            --from-literal=github_app_installation_id=${{ secrets.RUNNER_APP_INSTALLATION_ID }} \
            --from-literal=github_app_private_key="${{ secrets.RUNNER_APP_PRIVATE_KEY }}"

      - name: Install Runners
        run: |
          helm upgrade --install arc oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
            --version 0.4.0 \
            -n arc-systems --create-namespace \
            -f arc/controller.yaml \
            --wait
          
          helm upgrade --install benzene-ubuntu oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
            --version 0.4.0 \
            -n arc-runners --create-namespace \
            -f arc/runner.yaml \
            --wait
