name: Install GitHub Runners

on:
  workflow_dispatch:

concurrency: install

jobs:
  Install:
    runs-on: ubuntu-latest
    environment: GHA
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GHA_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name github_runners

      - name: Install ARC
        run: |
          helm upgrade --install arc oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
            --version ${{ vars.ARC_VERSION }} \
            -n arc-systems --create-namespace \
            -f arc/controller.yaml \
            --set flags.logLevel=${{ vars.LOG_LEVEL || 'info' }} \
            --wait

      - name: Install runners
        run: |
          kubectl create ns arc-runners --save-config --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl create secret docker-registry github-registry \
            -n arc-runners \
            --docker-server=ghcr.io \
            --docker-username=${{ github.repository_owner }} \
            --docker-password=${{ secrets.GH_PACKAGES_TOKEN }} \
            --save-config --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl create secret generic github-app \
            -n arc-runners \
            --from-literal=github_app_id=${{ secrets.RUNNER_APP_ID }} \
            --from-literal=github_app_installation_id=${{ secrets.RUNNER_APP_INSTALLATION_ID }} \
            --from-literal=github_app_private_key="${{ secrets.RUNNER_APP_PRIVATE_KEY }}" \
            --save-config --dry-run=client -o yaml | kubectl apply -f -
          
          helm upgrade --install benzene-ubuntu oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
            --version ${{ vars.ARC_VERSION }} \
            -n arc-runners \
            -f arc/runner.yaml \
            --set maxRunners=${{ vars.MAX_RUNNERS }} \
            --set minRunners=${{ vars.MIN_RUNNERS }} \
            --wait
