name: Uninstall GitHub Runners

on:
  workflow_dispatch:

concurrency: uninstall

jobs:
  Uninstall:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name github_runners

      - name: Uninstall Runners
        run: |
          helm uninstall benzene-ubuntu -n arc-runners
          
          helm uninstall arc -n arc-systems

      - name: Delete GitHub secrets
        run: |
          kubectl delete secret github-app -n arc-runners
          
          kubectl delete secret github-registry
