name: Uninstall GitHub Runners

on:
  workflow_dispatch:

concurrency: uninstall

jobs:
  Uninstall:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE }}
          aws-region: ap-south-1

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name github_runners

      - name: Uninstall Runners
        run: |
          kubectl delete -f runners.yaml
          
          helm uninstall actions-runner-controller \
            -n actions-runner-system \
            --wait
          
          kubectl delete ns actions-runner-system

      - name: Uninstall cert-manger
        run: |
          helm uninstall cert-manager \
            -n cert-manager \
            --wait
